class Conf():
    main_url = 'https://minifreemarket.com/'
    auth_url = 'https://minifreemarket.com/cabinet'
    login_url = 'https://minifreemarket.com/cabinet/register'
    correct_login = 'erigov@mail.ru'
    correct_pass = 'fktrctq83'
    incorrect_login = 'qwe123@#$'
    incorrect_pass = '12345678'
    rus_login = 'абвгд@'
    more_255_pass = '1' * 256
    null_email = ''
    find_bar_eng = 'necrons'
    necron_url = 'https://minifreemarket.com/catalog?fg_text=necrons&'
    shops_url = 'https://minifreemarket.com/shops'
    bask_url = 'https://minifreemarket.com/order'
