class Conf():
    main_url = 'https://minifreemarket.com/'
    auth_url = 'https://minifreemarket.com/cabinet'
    login_url = 'https://minifreemarket.com/cabinet/register'
    correct_login = 'erigov@mail.ru'
    correct_pass = 'fktrctq83'
    incorrect_login = 'qwe123@#$'
    key_space_login = 'erigov@mail.ru '
    key_space_passw = 'fktrctq83 '
    digit = '1234567890'
    rus_login = 'абвгд'
    more_255_pass = '1' * 256
    number_254_pass = '1' * 254
    number_255_pass = '1' * 255
    null_str = ''
    find_bar_eng = 'necrons'
    find_bar_rus = 'некроны'
    necron_url_eng = 'https://minifreemarket.com/catalog?fg_text=necrons&'
    shops_url = 'https://minifreemarket.com/shops'
    bask_url = 'https://minifreemarket.com/order'
    sel_url = 'https://minifreemarket.com/cabinet/products/add'
    spec_sym = '!@#$%^&*()'
    main_cat_url = 'https://minifreemarket.com/catalog?fg_text=&'
    warh_url = 'https://minifreemarket.com/catalog/games-with-miniatures/warhammer-40000'
    hlp_url = 'https://minifreemarket.com/help'
    fvr_url = 'https://minifreemarket.com/favorites'
