class Conf():
    main_url = 'https://minifreemarket.com/'
    auth_url = 'https://minifreemarket.com/cabinet'
    login_url = 'https://minifreemarket.com/cabinet/register'
    correct_login = 'erigov@mail.ru'
    correct_pass = 'fktrctq83'
    incorrect_login = 'qwe123@#$'
    incorrect_pass = '12345678'
    rus_login = 'абвгд@'
    more_255_pass = '1' * 256
    null_email = ''
    find_bar_eng = 'necrons'
    find_bar_rus = 'некроны'
    necron_url_eng = 'https://minifreemarket.com/catalog?fg_text=necrons&'
    necron_url_rus = 'https://minifreemarket.com/catalog?fg_text=%D0%BD%D0%B5%D0%BA%D1%80%D0%BE%D0%BD%D1%8B&'
    shops_url = 'https://minifreemarket.com/shops'
    bask_url = 'https://minifreemarket.com/order'
    sel_url = 'https://minifreemarket.com/cabinet/products/add'
